### ISSUE TITLE
Duplicate circVBuf and circVBufArrayInterface

### ISSUE THREAD

**Issue by kashefy** [TWOEARS/main#2]
Classes `circVBuf` and `circVBufArrayInterface` are defined under main/Tools/misc and auditory-front-end/src/Signals

The duplication may cause problems if the implementation in one repo changes.

Would it make sense to keep the ones in AFE and remove the ones in main?

cc: @hagenw, @Hardcorehobel

**Comment by hagenw** [comment]
Good question, are you able to do a search (for example via grep) through all the other main components (blackboard-system etc.) and check where it is used.
After that we should be able to decide on this. At t6he moment I'm also in favor of removing it in TWOEARS/main.

**Comment by kashefy** [comment]
Looks like the two classes are explicitly referenced in AFE and main
[Here](https://gist.github.com/kashefy/752b53304db4e15132f91b223fea204b) is a link to the grep output.

**Comment by hagenw** [comment]
Thanks, then I would propose we remove those functions from main as the AFE should work as a standalone module without main. What do you think?

**Comment by kashefy** [comment]
Yes, I think we should remove both files from main.

**Comment by hagenw** [comment]
OK, I will do it.

**Comment by kashefy** [comment]
thanks

**Comment by hagenw** [comment]
I deleted `Tools/misc/circVBuf.m` and `Tools/misc/circVBufArrayInterface.m`.
